backend:
  name: github
  repo: gauteaalokken/foto # MUST match your exact username/repository name on GitHub
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "photos"
    label: "Photos"
    folder: "src/content/photos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
