backend:
  name: github
  repo: gauteaalokken/foto # MUST match your exact username/repository name on GitHub
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "gallery"
    label: "Homepage Gallery"
    files:
      - name: "main"
        label: "Homepage Gallery"
        file: "src/content/gallery/index.yml"
        fields:
          - { label: "Photos", name: "photos", widget: "image", multiple: true }

  - name: "blog"
    label: "Blog (ukens bilder)"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Photos", name: "photos", widget: "image", multiple: true }
      - { label: "Text", name: "body", widget: "markdown" }
